### ISSUE TITLE
Weird behavior when joining roads with different widths

### ISSUE THREAD

**Issue by kingoflolz** [citybound/citybound#123]
Try to join a 2 wide road with a 4 wide road results in this:
![screenshot from 2017-02-02 19-13-40](https://cloud.githubusercontent.com/assets/8016247/22541671/dbf7c4ec-e97b-11e6-9621-9254ab29c707.png)
and a crash when implemented.

Thinking eventually we would want to have automatic creation of merging lanes or something.

**Comment by aeickhoff** [comment]
Which crash do you get on implementation? This is definitely a bug

**Comment by kingoflolz** [comment]
Testing further, the issue only occurs when building the 2 lane road first, and connecting a *sligthly offset* 4 lane road to it, where it fails to snap the lanes properly
This is the error I get:
```
transfer lane not connected for obstacles yet
transfer lane not connected for obstacles yet
thread 'main' panicked at 'should have a right lane', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:715
stack backtrace:
   1:     0x555bb517be9c - std::sys::imp::backtrace::tracing::imp::write::h9c41d2f69e5caabf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x555bb517ff0e - std::panicking::default_hook::{{closure}}::h1f61f3c769fffe7a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x555bb517fb14 - std::panicking::default_hook::hd5bda4e453dfb4be
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x555bb51803ab - std::panicking::rust_panic_with_hook::hffbc74969c7b5d87
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x555bb5180244 - std::panicking::begin_panic::h3bbdbb2a23440035
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x555bb5180169 - std::panicking::begin_panic_fmt::h34f5b320b0f94559
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x555bb51800f7 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x555bb51aaced - core::panicking::panic_fmt::h1016b85b51d1931f
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x555bb51aad7d - core::option::expect_failed::h25dde1949820388a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:715
  10:     0x555bb4fea365 - citybound::game::lanes_and_cars::pathfinding::<impl kay::messaging::Recipient<citybound::game::lanes_and_cars::pathfinding::JoinLandmark> for citybound::game::lanes_and_cars::lane::TransferLane>::receive::hf24827ee6dd0ea73
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:293
                        at /home/travis/build/citybound/citybound/src/game/lanes_and_cars/lane.rs:57
                        at /home/travis/build/citybound/citybound/src/game/lanes_and_cars/pathfinding/mod.rs:265
  11:     0x555bb4ff65b2 - kay::actor_system::ActorSystem::add_handler_helper::{{closure}}::hf67be81151383c46
                        at /home/travis/build/citybound/citybound/lib/kay/src/messaging.rs:28
                        at /home/travis/build/citybound/citybound/lib/kay/src/swarm.rs:157
                        at /home/travis/build/citybound/citybound/lib/kay/src/swarm.rs:309
                        at /home/travis/build/citybound/citybound/lib/kay/src/swarm.rs:295
                        at /home/travis/build/citybound/citybound/lib/kay/src/actor_system.rs:138
  12:     0x555bb50b47d0 - std::panicking::try::do_call::hb0af9e1a6a73e1f6
                        at /home/travis/build/citybound/citybound/lib/kay/src/actor_system.rs:177
                        at /home/travis/build/citybound/citybound/lib/kay/src/actor_system.rs:200
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:296
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:460
  13:     0x555bb518727a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  14:     0x555bb50b5b3b - kay::actor_system::ActorSystem::process_all_messages::h0edaf7b2e56cd5b4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /home/travis/build/citybound/citybound/lib/kay/src/actor_system.rs:199
  15:     0x555bb5067ab7 - citybound::main::h29b55ecf7c5cb743
                        at /home/travis/build/citybound/citybound/src/main.rs:138
  16:     0x555bb518727a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  17:     0x555bb5180b16 - std::rt::lang_start::ha0568cc91d8c5b09
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/rt.rs:57
  18:     0x7fe4ed5bbabf - __libc_start_main
  19:     0x555bb4fbdea8 - <unknown>
  20:                0x0 - <unknown>
Simulation Panic!
"should have a right lane"
```

**Comment by aeickhoff** [comment]
Thanks!
