### ISSUE TITLE
Adding grid results in "attempt to add with overflow"

### ISSUE THREAD

**Issue by samdroid-apps** [citybound/citybound#162]
On master as of reporting time (8c915e5f47b0a6becdf570187e58939f36bd50fb).  On Fedora GNU/Linux.

Steps to reproduce:

* Open citybound
* Press "g" to add a grid

Expected behaviour:

Roads are created

Actual behaviour:

Simulation panics, "attempt to add with overflow"

```
thread 'main' panicked at 'attempt to add with overflow', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/ops.rs:263
stack backtrace:
   1:     0x559b83d4ee7c - std::sys::imp::backtrace::tracing::imp::write::h9c41d2f69e5caabf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x559b83d52fce - std::panicking::default_hook::{{closure}}::h1f61f3c769fffe7a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x559b83d52bd4 - std::panicking::default_hook::hd5bda4e453dfb4be
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x559b83d5346b - std::panicking::rust_panic_with_hook::hffbc74969c7b5d87
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x559b83d53304 - std::panicking::begin_panic::h3bbdbb2a23440035
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x559b83d53229 - std::panicking::begin_panic_fmt::h34f5b320b0f94559
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x559b83d531b7 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x559b83d7ddad - core::panicking::panic_fmt::h1016b85b51d1931f
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x559b83d7dce4 - core::panicking::panic::h22ba9383231afe8b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:49
  10:     0x559b83bf5a37 - <u16 as core::ops::Add>::add::h4fd2d3e083ff81ee
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/ops.rs:263
  11:     0x559b83bf87f7 - <monet::thing::Thing as core::ops::AddAssign>::add_assign::haf0263424aee8011
                        at /home/saam/citybound/lib/monet/src/thing.rs:51
  12:     0x559b83ad8b63 - <monet::thing::Thing as core::iter::traits::Sum>::sum::h7708ff7f75d4c1a1
                        at /home/saam/citybound/lib/monet/src/thing.rs:63
  13:     0x559b83ad13ab - core::iter::iterator::Iterator::sum::h6870ae5202e3ce9a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/iter/iterator.rs:1920
  14:     0x559b83aeba3f - citybound::game::lanes_and_cars::planning::current_plan::rendering::render_intersections::hdfe7ac2a66fe0f99
                        at /home/saam/citybound/src/game/lanes_and_cars/planning/current_plan/rendering.rs:132
  15:     0x559b83b438db - citybound::game::lanes_and_cars::planning::current_plan::rendering::<impl kay::messaging::Recipient<monet::renderer::control::RenderToScene> for citybound::game::lanes_and_cars::planning::current_plan::CurrentPlan>::receive::hd1900b4d0001b8b6
                        at /home/saam/citybound/src/game/lanes_and_cars/planning/current_plan/rendering.rs:40
  16:     0x559b83c38038 - kay::actor_system::ActorSystem::single_message_cycle::h205a53ecde6e1916
                        at /home/saam/citybound/lib/kay/src/actor_system.rs:177
  17:     0x559b83c3822a - kay::actor_system::ActorSystem::process_all_messages::{{closure}}::h6019b6e41638f51d
                        at /home/saam/citybound/lib/kay/src/actor_system.rs:200
  18:     0x559b83c38344 - core::ops::FnOnce::call_once::h09c96fcb4222edb3
  19:     0x559b83d5a33a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  20:     0x559b83c36737 - std::panicking::try::h7bc6fc233285707c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
  21:     0x559b83c366ed - std::panic::catch_unwind::hba6176e845cc6bb8
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
  22:     0x559b83c3818b - kay::actor_system::ActorSystem::process_all_messages::h0aeb2936fb90916c
                        at /home/saam/citybound/lib/kay/src/actor_system.rs:199
  23:     0x559b83b936cb - citybound::main::hd83bd41b491d98db
                        at /home/saam/citybound/src/main.rs:142
  24:     0x559b83d5a33a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  25:     0x559b83d53bd6 - std::rt::lang_start::ha0568cc91d8c5b09
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/rt.rs:57
  26:     0x7f9edeb39400 - __libc_start_main
  27:     0x559b83a68f59 - _start
  28:                0x0 - <unknown>
Simulation Panic!
"attempt to add with overflow"
```

**Comment by aeickhoff** [comment]
This should only happen when you compile in debug mode, correct? Since it only affects geometry vertices, I'm just ignoring that for now, which is not nice but not showstopping.

**Comment by samdroid-apps** [comment]
Yes, the bug does not occur in release mode.  I assume that is because rust disables overflow checking in release mode?

Maybe it is due to monet using u16 to store the indicies.  I tracked it down to a regression (see https://github.com/citybound/citybound/pull/163).  u16 is very small, and some of the constants are larger than u16.

**Comment by Paul-E** [comment]
Debug mode is valuable because it helps with [other bugs](https://github.com/citybound/citybound/issues/249). Would it make sense to explicitly use [`wrapping_add`](https://doc.rust-lang.org/std/primitive.u16.html#method.wrapping_add) (which is what [release mode](http://huonw.github.io/blog/2016/04/myths-and-legends-about-integer-overflow-in-rust/) is doing) in a few places [[1](https://github.com/citybound/citybound/blob/4593520f1df813b2072f42c4a3583cd102ce7d99/engine/monet/src/geometry/mod.rs#L117)] [[2](https://github.com/citybound/citybound/blob/4593520f1df813b2072f42c4a3583cd102ce7d99/engine/monet/src/geometry/mod.rs#L92)] [[3](https://github.com/citybound/citybound/blob/master/engine/monet/src/geometry/mod.rs#L79)], and add a TODO to figure out something better later?
