### ISSUE TITLE
Wrapping road on itself causes application to hang on macOS

### ISSUE THREAD

**Issue by YeomansIII** [citybound/citybound#29]
**Platform**: macOS Sierra 10.12.2
**What was I doing**: Just messing around, I made one road segment, then tried attaching the continuation back to the end of the first segment. The application froze and I was getting the macOS pinwheel. I force closed the application. Now, when I open the application, no window shows up.

Let me know if there are logs I can copy somewhere and paste them here.

**Comment by Whiteaeros** [comment]
Platform: Windows 7

Same issue as YeomanIII drawing rd. segment and then connecting it directly to itself stalled the program. Just clicked the x to close. 

No issue with restarting the game

Loving the demo!

**Comment by chdudek** [comment]
I got the same problem with non launching demo on macOS, but without the previous crash: https://github.com/citybound/citybound/issues/34

You can compile the game from source to use it without this problem (at least this works for me for now).

**Comment by chdudek** [comment]
Clicking on the end of a created road crashes for me.
I get the following error message from the self compiled version, started from the terminal:
`$ ./citybound
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Simulation Panic!
"called `Option::unwrap()` on a `None` value"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323`

**Comment by aeickhoff** [comment]
I already had a last-minute solution for this, you can uncomment it here:

https://github.com/citybound/citybound/blob/795445e/src/game/lanes_and_cars/planning/plan_result_steps.rs#L69

But it caused a severe performance regression, that's why I removed it for the launch.
I'll look into it again!

**Comment by aeickhoff** [comment]
Very likely related to #35
