### ISSUE TITLE
Crash trying to plan road from built ring

### ISSUE THREAD

**Issue by nielsmh** [citybound/citybound#37]
> D:\Games\Citybound\Tech demo 1>citybound-windows.exe
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore\option.rs:323
stack backtrace:
   0:           0x6f54e4 - <unknown>
   1:           0x6f1d59 - <unknown>
   2:           0x6f248a - <unknown>
   3:           0x6f2326 - <unknown>
   4:           0x6f2249 - <unknown>
   5:           0x6f21cb - <unknown>
   6:           0x70b0a5 - <unknown>
   7:           0x70afed - <unknown>
   8:           0x4b3266 - <unknown>
   9:           0x4bc74b - <unknown>
  10:           0x4ff999 - <unknown>
  11:           0x42f206 - <unknown>
  12:           0x6fdb38 - <unknown>
  13:           0x461554 - <unknown>
  14:           0x6f2108 - <unknown>
  15:           0x6fdb38 - <unknown>
  16:           0x6f1503 - <unknown>
  17:           0x4013b4 - <unknown>
  18:           0x4014e7 - <unknown>
  19:     0x7ffba7c38363 - <unknown>
Simulation Panic!
"called `Option::unwrap()` on a `None` value"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore\option.rs:323
stack backtrace:
   0:           0x6f54e4 - <unknown>
   1:           0x6f1d59 - <unknown>
   2:           0x6f248a - <unknown>
   3:           0x6f2326 - <unknown>
   4:           0x6f2249 - <unknown>
   5:           0x6f21cb - <unknown>
   6:           0x70b0a5 - <unknown>
   7:           0x70afed - <unknown>
   8:           0x4a2805 - <unknown>
   9:           0x4b05a9 - <unknown>
  10:           0x4bc74b - <unknown>
  11:           0x4ff999 - <unknown>
  12:           0x461446 - <unknown>
  13:           0x6f2108 - <unknown>
  14:           0x6fdb38 - <unknown>
  15:           0x6f1503 - <unknown>
  16:           0x4013b4 - <unknown>
  17:           0x4014e7 - <unknown>
  18:     0x7ffba7c38363 - <unknown>

Reproduction:
1. Plan a road ring (i.e. a single road starting and ending at the same point)
2. Implement the plan
3. The constructed roads will have a destination point in the middle (red dots above lanes) away from the start/end point
4. Attempt to plan a new road starting at the middle destination point
5. Above crash happens

**Comment by nielsmh** [comment]
Turns out similar/identical crashes can happen in more circumstances all related to starting a new road plan from on/near a built road.

**Comment by Outpox** [comment]
I just faced this exact issue with a looped road.  
I'm on Linux and the game window crashed, but my terminal logged the issue:  
```
./citybound-linux 
Created new window in existing browser session.
ID 0_0_2 is not a destination yet
ID 0_0_0 is not a destination yet
ID 0_0_1 is not a destination yet
[...]
ID 0_0_3 is not a destination yet
ID 0_0_3 is not a destination yet
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Simulation Panic!
"called `Option::unwrap()` on a `None` value"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
```
